### PR TITLE
Refactor translator classes and add Yandex support

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by divec** [comment]
Nice work.

I believe the uppercasing trick doesn't work reliably on Yandex. For example, it translates (en=>es) 'big BOX' as 'Caja GRANDE' (i.e. it puts the uppercase in the wrong place).

We should experiment: it may map HTML tags reliably, or we may need to do the substring trick. Meanwhile the minimal implementation would be to just degrade down to the plaintext.

**Comment by edg2s** [comment]
That might just be because you provided a very short string. "It is a BIG box" translates correctly to "Es una caja GRANDE".

**Comment by edg2s** [comment]
The HTML mode appears to result in a worse translation: "Es un <span id="annotation-1">gran</span> cuadro".

**Comment by divec** [comment]
Ok, then I'll merge it but add an issue to build per-engine subsequence detection.

**Pull request merged**
